name: release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: initialize
      run: |
        sudo -E apt-get -y install build-essential python iasl lzop unifont autopoint bison flex gettext gcc-mingw-w64 gcc-multilib
    - name: bootstrap
      run: |
        mkdir -p PKG
        ./bootstrap

    - name: i686-w64-mingw32 configure
      run: |
        ./configure --prefix=/ --target=i686-w64-mingw32 --host=i686-w64-mingw32
    - name: i686-w64-mingw make
      run: |
        make
        cp mkimage.exe PKG/mkimage.exe
    - name: i686-w64-mingw clean
      run: make clean

    - name: i386-gcc configure
      run: |
        ./configure CFLAGS=-m32
    - name: i386-gcc make
      run: |
        make
        cp mkimage PKG/mkimage.i386
    - name: i386-gcc clean
      run: make clean

    - name: x86_64-gcc configure
      run: |
        ./configure
    - name: x86_64-gcc make
      run: |
        make
        cp mkimage PKG/mkimage
    - name: x86_64-gcc clean
      run: make clean

    - name: upload
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Development Build"
        files: |
          PKG/mkimage.exe
          PKG/mkimage
          PKG/mkimage.i386
